### ISSUE TITLE
Sidebar show files

### ISSUE THREAD

**Issue by stoivo** [shagabutdinov/sublime-devastate-mini#1]
First off, great theme ‼️

I am wondering if it is possible to keep the file icon in the sidebar. I added two screenshots to show you what I mean.
![screen shot 2016-05-21 at 22 28 06](https://cloud.githubusercontent.com/assets/3492040/15450715/9ec738fc-1fa3-11e6-8987-eb1bdf555150.png)
![screen shot 2016-05-21 at 22 27 52](https://cloud.githubusercontent.com/assets/3492040/15450714/9ec69500-1fa3-11e6-9ac4-2eaa6806055b.png)

**Comment by shagabutdinov** [comment]
I think you can check original devastate theme and see if they already fix this issue. If they did you can backport the difference, if not - please open issue to the original theme. You can also try to debug this issue by yourself and open PR here. I don't use sidebars in order to have as much space as possible for the source code.

**Comment by vlakarados** [comment]
Same goes for me, the package was meant to be as space economic as possible.
The main problem is that I don't use ST at all anymore, so might be a bit difficult to help you, though, in [this commit](https://github.com/vlakarados/devastate/commit/9aa964ec31dbaa618af94b46c683c853c209c0fb), I think, after icons were added to ST, I was hiding them using opacity. Try changing that value @stoivo and tell if it helps. I would gladly accept any PR if it takes more than that to add them. A second theme file with icons enabled would be pretty good to have.
